# Generated by Django 5.0.6 on 2024-06-20 13:11

import app1.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_commonmodel_delete_mymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('source', app1.models.PythonCodeField(blank=True, null=True)),
            ],
        ),
    ]
