# Generated by Django 5.0.6 on 2024-06-20 14:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_usermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='owner',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
